/* The following code was generated by JFlex 1.6.1 */

package analizador_lexico;

import static analizador_lexico.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/GitHub/Analizador-lexico/Analizador_lexico/src/analizador_lexico/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\77\1\62\1\63\1\63\1\63\22\0\1\77\1\37\1\65"+
    "\1\0\1\67\1\44\1\45\1\61\1\72\1\72\1\42\1\41\1\71"+
    "\1\41\1\60\1\43\1\55\1\57\6\56\2\54\1\102\1\70\1\34"+
    "\1\36\1\35\1\40\1\0\1\1\1\2\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\12\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\12"+
    "\1\73\1\102\1\73\1\0\1\76\1\0\1\46\1\2\1\3\1\47"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\50"+
    "\1\51\1\20\1\12\1\52\1\22\1\23\1\24\1\100\1\26\1\53"+
    "\1\30\1\12\1\74\1\75\1\74\1\0\6\66\1\64\32\66\1\101"+
    "\137\66\60\0\2\31\115\0\1\32\u1500\0\1\77\u097f\0\13\77\35\0"+
    "\1\63\1\63\5\0\1\77\57\0\1\77\312\0\1\33\u0ed5\0\1\77"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\16\3\2\2\2\4\1\5\1\6\1\7"+
    "\4\5\5\6\2\10\1\7\1\2\1\11\1\12\1\7"+
    "\1\2\1\13\1\14\1\15\1\16\2\1\1\2\1\12"+
    "\1\7\10\3\1\17\4\3\1\20\6\3\1\17\3\0"+
    "\2\4\1\0\2\10\1\0\1\2\1\20\1\6\3\2"+
    "\1\10\3\2\1\10\2\0\1\10\1\0\1\10\1\21"+
    "\1\0\5\3\1\0\3\3\2\17\3\3\1\0\2\3"+
    "\1\0\1\3\2\0\1\17\5\0\1\10\3\0\1\22"+
    "\1\20\2\10\7\3\1\0\1\10\2\0\1\22\2\10"+
    "\1\20\6\3\3\0\3\3\2\0\3\3\2\0\1\3"+
    "\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\206\0\311\0\u010c\0\u014f\0\u0192\0\u01d5"+
    "\0\u0218\0\u025b\0\u029e\0\u02e1\0\u0324\0\u0367\0\u03aa\0\u03ed"+
    "\0\u0430\0\u0473\0\u04b6\0\u04f9\0\u053c\0\u057f\0\u05c2\0\u0605"+
    "\0\u0648\0\u068b\0\103\0\u06ce\0\u0711\0\u0754\0\u0797\0\u07da"+
    "\0\u081d\0\u0860\0\u08a3\0\u08e6\0\103\0\103\0\u0929\0\u096c"+
    "\0\103\0\103\0\103\0\103\0\u09af\0\u09f2\0\u0a35\0\u03aa"+
    "\0\103\0\u0a78\0\u0abb\0\u0afe\0\u0b41\0\u0b84\0\u0bc7\0\u0c0a"+
    "\0\u0c4d\0\206\0\u0c90\0\u0cd3\0\u0d16\0\u0d59\0\206\0\u0d9c"+
    "\0\u0ddf\0\u0e22\0\u0e65\0\u0ea8\0\u0eeb\0\103\0\u0f2e\0\u0f71"+
    "\0\u0fb4\0\103\0\u0ff7\0\u103a\0\u107d\0\u10c0\0\u08a3\0\u1103"+
    "\0\u1146\0\u1189\0\u11cc\0\u120f\0\u1252\0\u1295\0\u12d8\0\u131b"+
    "\0\u135e\0\u13a1\0\u13e4\0\u08e6\0\u08e6\0\u0929\0\u0929\0\u1427"+
    "\0\u0a35\0\u146a\0\u14ad\0\u14f0\0\u1533\0\u1576\0\u15b9\0\u15fc"+
    "\0\u163f\0\u1682\0\u16c5\0\u1708\0\u174b\0\u178e\0\u17d1\0\u1814"+
    "\0\u1857\0\u189a\0\u18dd\0\u1920\0\u1963\0\u19a6\0\u19e9\0\u1a2c"+
    "\0\u1a6f\0\u1ab2\0\u1af5\0\u1b38\0\u1b7b\0\u1bbe\0\u1c01\0\u1c44"+
    "\0\u1c87\0\u11cc\0\u12d8\0\u131b\0\u1cca\0\u1d0d\0\u1d50\0\u1d93"+
    "\0\u1dd6\0\u1e19\0\u1e5c\0\u1e9f\0\206\0\u1ee2\0\u1f25\0\u1c44"+
    "\0\u1ab2\0\u1af5\0\103\0\u1f68\0\u1fab\0\u1fee\0\u2031\0\u2074"+
    "\0\u20b7\0\u20fa\0\u213d\0\u2180\0\u21c3\0\u2206\0\u2249\0\u228c"+
    "\0\u22cf\0\u2312\0\u2355\0\u2398\0\u23db\0\u241e\0\u2461\0\u24a4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\3"+
    "\1\11\4\3\1\12\1\3\1\13\1\14\1\15\1\16"+
    "\1\3\1\17\1\20\2\3\1\21\1\22\1\2\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\35\1\40\1\35\1\41"+
    "\1\42\2\41\1\43\1\44\1\45\2\46\1\47\1\2"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\46\1\60\1\46\1\61\104\0\30\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\3\0\16\3\1\62\1\3"+
    "\1\63\7\3\15\0\3\3\1\62\1\63\5\3\16\0"+
    "\1\3\1\0\1\3\3\0\13\3\1\64\14\3\15\0"+
    "\12\3\16\0\1\3\1\0\1\3\3\0\16\3\1\65"+
    "\11\3\15\0\3\3\1\65\6\3\16\0\1\3\1\0"+
    "\1\3\3\0\13\3\1\66\12\3\1\67\1\3\15\0"+
    "\5\3\1\67\4\3\16\0\1\3\1\0\1\3\3\0"+
    "\1\70\15\3\1\71\11\3\15\0\1\70\2\3\1\71"+
    "\6\3\16\0\1\3\1\0\1\3\3\0\5\3\1\72"+
    "\6\3\1\73\1\74\12\3\15\0\2\3\1\74\7\3"+
    "\16\0\1\3\1\0\1\3\3\0\4\3\1\75\16\3"+
    "\1\76\4\3\15\0\12\3\16\0\1\3\1\0\1\3"+
    "\3\0\22\3\1\77\5\3\15\0\12\3\16\0\1\3"+
    "\1\0\1\3\3\0\4\3\1\100\23\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\3\0\22\3\1\101\5\3"+
    "\15\0\12\3\16\0\1\3\1\0\1\3\3\0\7\3"+
    "\1\102\10\3\1\103\7\3\15\0\4\3\1\103\5\3"+
    "\16\0\1\3\1\0\1\3\3\0\16\3\1\104\11\3"+
    "\15\0\3\3\1\104\6\3\16\0\1\3\1\0\1\3"+
    "\3\0\7\3\1\105\20\3\15\0\12\3\16\0\1\3"+
    "\1\0\1\3\10\0\1\106\6\0\1\107\1\110\31\0"+
    "\1\110\55\0\1\111\114\0\1\112\1\113\102\0\1\112"+
    "\102\0\1\24\1\114\101\0\1\112\1\34\5\0\7\34"+
    "\21\0\1\34\45\0\1\112\116\0\1\115\1\116\2\115"+
    "\1\117\64\0\1\33\102\0\1\120\1\121\76\0\1\34"+
    "\5\0\7\34\21\0\1\34\6\0\30\3\6\0\1\34"+
    "\5\0\1\34\6\35\4\3\15\0\1\34\1\3\1\0"+
    "\1\3\3\0\16\3\1\65\11\3\6\0\1\34\5\0"+
    "\1\34\3\35\1\122\2\35\4\3\15\0\1\34\1\3"+
    "\1\0\1\3\3\0\4\3\1\75\16\3\1\76\4\3"+
    "\6\0\1\34\5\0\1\34\6\35\4\3\15\0\1\34"+
    "\1\3\1\0\1\3\3\0\4\3\1\100\23\3\6\0"+
    "\1\34\5\0\1\34\6\35\4\3\15\0\1\34\1\3"+
    "\1\0\1\3\3\0\4\123\1\124\12\123\1\125\10\123"+
    "\15\0\6\123\4\41\1\126\17\0\1\123\3\0\1\123"+
    "\1\127\2\123\1\124\12\123\1\125\6\123\1\130\1\123"+
    "\15\0\5\123\1\130\1\131\3\132\1\126\17\0\1\123"+
    "\56\0\4\133\23\0\61\134\1\135\3\0\16\134\62\136"+
    "\3\0\1\137\15\136\1\0\30\140\15\0\6\140\4\123"+
    "\4\0\1\140\1\0\1\140\7\0\1\140\1\0\2\140"+
    "\75\0\2\55\44\0\1\34\5\0\7\34\20\0\1\55"+
    "\1\56\6\0\30\3\15\0\6\3\22\0\1\141\1\0"+
    "\1\3\3\0\16\3\1\142\11\3\15\0\3\3\1\142"+
    "\6\3\16\0\1\3\1\0\1\3\3\0\4\3\1\143"+
    "\23\3\15\0\12\3\16\0\1\3\1\0\1\3\3\0"+
    "\1\144\27\3\15\0\1\144\11\3\16\0\1\3\1\0"+
    "\1\3\3\0\23\3\1\145\4\3\15\0\12\3\16\0"+
    "\1\3\1\0\1\3\3\0\21\3\1\146\6\3\1\0"+
    "\1\147\13\0\12\3\16\0\1\3\1\0\1\3\3\0"+
    "\22\3\1\150\5\3\15\0\12\3\16\0\1\3\1\0"+
    "\1\3\3\0\13\3\1\151\14\3\15\0\12\3\16\0"+
    "\1\3\1\0\1\3\3\0\20\3\1\72\7\3\15\0"+
    "\4\3\1\72\5\3\16\0\1\3\1\0\1\3\3\0"+
    "\17\3\1\152\10\3\15\0\12\3\16\0\1\3\1\0"+
    "\1\3\3\0\22\3\1\153\5\3\15\0\12\3\16\0"+
    "\1\3\1\0\1\3\3\0\25\3\1\154\2\3\15\0"+
    "\12\3\16\0\1\3\1\0\1\3\3\0\13\3\1\142"+
    "\14\3\15\0\12\3\16\0\1\3\1\0\1\3\3\0"+
    "\22\3\1\155\5\3\15\0\12\3\16\0\1\3\1\0"+
    "\1\3\3\0\20\3\1\156\7\3\15\0\4\3\1\156"+
    "\5\3\16\0\1\3\1\0\1\3\3\0\10\3\1\157"+
    "\17\3\1\160\14\0\12\3\16\0\1\3\1\0\1\3"+
    "\3\0\23\3\1\161\4\3\15\0\12\3\16\0\1\3"+
    "\1\0\1\3\3\0\10\3\1\162\17\3\1\163\14\0"+
    "\12\3\16\0\1\3\1\0\1\3\3\0\10\3\1\164"+
    "\17\3\1\165\14\0\12\3\16\0\1\3\1\0\1\3"+
    "\22\0\1\166\105\0\1\167\100\0\1\170\30\0\1\170"+
    "\65\0\1\112\103\0\1\2\51\0\1\171\46\0\4\115"+
    "\1\126\24\0\1\172\2\0\1\171\21\0\1\173\23\0"+
    "\1\173\1\174\3\175\1\126\22\0\42\176\1\177\17\176"+
    "\1\120\20\176\62\121\3\0\16\121\1\0\23\3\1\145"+
    "\4\3\6\0\1\34\5\0\1\34\6\35\4\3\15\0"+
    "\1\34\1\3\1\0\1\3\3\0\30\123\15\0\12\123"+
    "\20\0\1\123\3\0\30\123\10\0\1\200\4\0\6\123"+
    "\4\201\20\0\1\123\3\0\22\123\1\202\5\123\15\0"+
    "\12\123\20\0\1\123\7\0\1\171\46\0\4\126\24\0"+
    "\30\123\15\0\7\123\1\203\1\123\1\203\20\0\1\123"+
    "\3\0\6\204\22\123\15\0\2\204\4\123\4\204\20\0"+
    "\1\123\3\0\4\123\1\124\12\123\1\125\10\123\15\0"+
    "\6\123\4\131\1\133\17\0\1\123\3\0\4\123\1\124"+
    "\12\123\1\125\10\123\15\0\6\123\1\131\3\132\1\133"+
    "\17\0\1\123\7\0\1\171\46\0\4\133\24\0\30\140"+
    "\15\0\12\140\4\0\1\140\1\0\1\140\7\0\1\140"+
    "\1\0\2\140\2\0\13\3\1\72\14\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\3\0\1\205\27\3\15\0"+
    "\1\205\11\3\16\0\1\3\1\0\1\3\3\0\21\3"+
    "\1\157\6\3\1\0\1\160\13\0\12\3\16\0\1\3"+
    "\1\0\1\3\3\0\1\3\1\164\26\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\3\0\4\3\1\72\23\3"+
    "\15\0\12\3\16\0\1\3\1\0\1\3\7\0\1\106"+
    "\76\0\4\3\1\206\23\3\15\0\12\3\16\0\1\3"+
    "\1\0\1\3\3\0\21\3\1\161\6\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\3\0\13\3\1\207\14\3"+
    "\15\0\12\3\16\0\1\3\1\0\1\3\3\0\4\3"+
    "\1\210\23\3\15\0\12\3\16\0\1\3\1\0\1\3"+
    "\3\0\1\211\27\3\15\0\1\211\11\3\16\0\1\3"+
    "\1\0\1\3\3\0\23\3\1\212\4\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\3\0\10\3\1\213\17\3"+
    "\1\214\14\0\12\3\16\0\1\3\1\0\1\3\3\0"+
    "\21\3\1\72\6\3\1\0\1\106\13\0\12\3\16\0"+
    "\1\3\1\0\1\3\24\0\1\106\7\0\1\106\51\0"+
    "\4\3\1\215\23\3\15\0\12\3\16\0\1\3\1\0"+
    "\1\3\3\0\3\3\1\72\24\3\15\0\1\3\1\72"+
    "\10\3\16\0\1\3\1\0\1\3\6\0\1\106\42\0"+
    "\1\106\34\0\13\3\1\146\14\3\15\0\12\3\16\0"+
    "\1\3\1\0\1\3\16\0\1\147\102\0\1\216\73\0"+
    "\1\217\106\0\1\214\17\0\1\214\112\0\1\200\12\0"+
    "\4\220\100\0\1\221\1\0\1\221\24\0\6\222\37\0"+
    "\2\222\4\0\4\222\30\0\1\171\46\0\4\174\1\133"+
    "\27\0\1\171\46\0\1\174\3\175\1\133\22\0\42\176"+
    "\1\177\102\176\1\177\1\223\37\176\54\0\4\220\24\0"+
    "\30\123\15\0\6\123\4\201\20\0\1\123\3\0\12\3"+
    "\1\72\15\3\2\0\1\106\12\0\12\3\16\0\1\3"+
    "\1\0\1\3\3\0\15\3\1\224\12\3\15\0\2\3"+
    "\1\224\7\3\16\0\1\3\1\0\1\3\3\0\4\3"+
    "\1\225\23\3\15\0\12\3\16\0\1\3\1\0\1\3"+
    "\3\0\20\3\1\226\7\3\15\0\4\3\1\226\5\3"+
    "\16\0\1\3\1\0\1\3\3\0\20\3\1\227\7\3"+
    "\15\0\4\3\1\227\5\3\16\0\1\3\1\0\1\3"+
    "\3\0\20\3\1\230\7\3\15\0\4\3\1\230\5\3"+
    "\16\0\1\3\1\0\1\3\3\0\15\3\1\231\12\3"+
    "\15\0\2\3\1\231\7\3\16\0\1\3\1\0\1\3"+
    "\20\0\1\232\31\0\1\232\37\0\1\233\116\0\1\234"+
    "\30\0\1\234\31\0\3\3\1\157\24\3\15\0\1\3"+
    "\1\157\10\3\16\0\1\3\1\0\1\3\3\0\14\3"+
    "\1\235\13\3\15\0\12\3\16\0\1\3\1\0\1\3"+
    "\3\0\5\3\1\236\22\3\15\0\12\3\16\0\1\3"+
    "\1\0\1\3\3\0\20\3\1\237\7\3\15\0\4\3"+
    "\1\237\5\3\16\0\1\3\1\0\1\3\3\0\15\3"+
    "\1\72\12\3\15\0\2\3\1\72\7\3\16\0\1\3"+
    "\1\0\1\3\3\0\6\3\1\72\21\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\11\0\1\106\110\0\1\240"+
    "\73\0\1\241\75\0\4\3\1\242\23\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\3\0\1\243\27\3\15\0"+
    "\1\243\11\3\16\0\1\3\1\0\1\3\3\0\1\244"+
    "\27\3\15\0\1\244\11\3\16\0\1\3\1\0\1\3"+
    "\7\0\1\245\76\0\1\246\44\0\1\246\35\0\15\3"+
    "\1\247\12\3\15\0\2\3\1\247\7\3\16\0\1\3"+
    "\1\0\1\3\3\0\2\3\1\146\25\3\15\0\12\3"+
    "\16\0\1\3\1\0\1\3\3\0\27\3\1\72\15\0"+
    "\12\3\16\0\1\3\1\0\1\3\20\0\1\250\31\0"+
    "\1\250\35\0\1\147\100\0\22\3\1\157\5\3\15\0"+
    "\12\3\16\0\1\3\1\0\1\3\25\0\1\160\57\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9447];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\30\1\1\11\11\1\2\11\2\1\4\11"+
    "\4\1\1\11\24\1\1\11\3\0\1\11\1\1\1\0"+
    "\2\1\1\0\13\1\2\0\1\1\1\0\2\1\1\0"+
    "\5\1\1\0\10\1\1\0\2\1\1\0\1\1\2\0"+
    "\1\1\5\0\1\1\3\0\13\1\1\0\1\1\2\0"+
    "\3\1\1\11\6\1\3\0\3\1\2\0\3\1\2\0"+
    "\1\1\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 274) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = yytext(); return BRACKET;
            }
          case 19: break;
          case 2: 
            { lexeme = yytext(); return ERROR;
            }
          case 20: break;
          case 3: 
            { lexeme = yytext(); return IDENTIFIER;
            }
          case 21: break;
          case 4: 
            { lexeme = yytext(); return COMPARISON_OPERATOR;
            }
          case 22: break;
          case 5: 
            { lexeme = yytext(); return ARITHMETIC_OPERATOR;
            }
          case 23: break;
          case 6: 
            { lexeme = yytext(); return LOGICAL_OPERATOR;
            }
          case 24: break;
          case 7: 
            { lexeme = yytext(); return POINT;
            }
          case 25: break;
          case 8: 
            { lexeme = yytext(); return CONSTANT;
            }
          case 26: break;
          case 9: 
            { lexeme = yytext(); return NEWLINE;
            }
          case 27: break;
          case 10: 
            { lexeme = yytext(); return WHITESPACE;
            }
          case 28: break;
          case 11: 
            { lexeme = yytext(); return SEMICOLON;
            }
          case 29: break;
          case 12: 
            { lexeme = yytext(); return COMMA;
            }
          case 30: break;
          case 13: 
            { lexeme = yytext(); return PARENTHESIS;
            }
          case 31: break;
          case 14: 
            { lexeme = yytext(); return BRACE;
            }
          case 32: break;
          case 15: 
            { lexeme = yytext(); return RESERVED_WORD;
            }
          case 33: break;
          case 16: 
            { lexeme = yytext(); return COMMENT;
            }
          case 34: break;
          case 17: 
            { lexeme = yytext(); return VARIABLE_ID;
            }
          case 35: break;
          case 18: 
            { lexeme = yytext(); return FLOATING_POINT_NUM;
            }
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
