/* The following code was generated by JFlex 1.6.1 */

package analizador_lexico;

import static analizador_lexico.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/GitHub/Analizador-lexico/Analizador_lexico/src/analizador_lexico/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\71\1\64\1\65\1\65\1\65\22\0\1\71\1\35\1\66"+
    "\1\0\1\0\1\42\1\43\1\63\1\55\1\56\1\40\1\37\1\54"+
    "\1\37\1\53\1\41\1\45\1\52\6\50\2\44\1\54\1\54\1\32"+
    "\1\34\1\33\1\36\1\0\1\30\1\51\2\47\1\47\1\47\7\70"+
    "\1\27\11\70\1\46\2\70\1\57\1\54\1\60\1\0\1\67\1\0"+
    "\1\17\1\10\1\16\1\4\1\12\1\20\1\15\1\21\1\3\1\70"+
    "\1\26\1\11\1\23\1\5\1\2\1\24\1\70\1\14\1\13\1\6"+
    "\1\7\1\1\1\25\1\22\1\31\1\70\1\61\1\62\1\61\1\0"+
    "\6\0\1\65\32\0\1\71\137\0\u1580\0\1\71\u097f\0\13\71\35\0"+
    "\1\65\1\65\5\0\1\71\57\0\1\71\u0fa0\0\1\71\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\17\3\2\4\1\5\1\6\1\1\4\5"+
    "\1\6\2\7\5\1\1\2\1\10\1\11\2\2\2\3"+
    "\1\12\20\3\2\4\2\7\1\13\1\14\1\0\1\7"+
    "\3\0\1\7\1\0\1\7\1\0\1\7\1\0\1\3"+
    "\1\12\15\3\1\12\1\7\3\15\1\13\1\14\2\7"+
    "\2\3\1\7\5\3\3\0\1\13\1\14\1\0\6\3"+
    "\2\0\7\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\u015c\0\u0196"+
    "\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c\0\u0366"+
    "\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc\0\u0536"+
    "\0\u0570\0\72\0\u05aa\0\u05e4\0\u061e\0\72\0\u0658\0\u0692"+
    "\0\u06cc\0\u0706\0\u0740\0\u077a\0\72\0\u07b4\0\u07ee\0\u0828"+
    "\0\u0862\0\u01d0\0\u089c\0\u08d6\0\u0910\0\u094a\0\u0984\0\u09be"+
    "\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e"+
    "\0\u0bc8\0\u0c02\0\72\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea\0\u0d24"+
    "\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80\0\u0740\0\u0740"+
    "\0\u07b4\0\u07b4\0\u07ee\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2"+
    "\0\u0fdc\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe\0\u1138\0\u1172"+
    "\0\u11ac\0\u11e6\0\u1220\0\u125a\0\u1294\0\u12ce\0\u1308\0\u1342"+
    "\0\72\0\u0dd2\0\u0e0c\0\u137c\0\u13b6\0\u01d0\0\u13f0\0\u142a"+
    "\0\u1464\0\u149e\0\u14d8\0\u1294\0\u1308\0\u1512\0\u12ce\0\u154c"+
    "\0\u1586\0\u15c0\0\u15fa\0\u1634\0\u166e\0\u16a8\0\u16e2\0\u154c"+
    "\0\u171c\0\u1756\0\u1790\0\u17ca\0\u1804\0\u183e\0\u1878\0\u18b2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\11\1\13\1\14\1\15\1\11\1\16\1\4"+
    "\1\17\1\11\1\4\2\11\1\20\1\11\1\21\2\11"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\2\11\1\34\1\11\1\34"+
    "\2\36\1\37\1\36\1\40\1\36\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\11\1\45\73\0\1\11"+
    "\1\50\27\11\12\0\7\11\14\0\2\11\2\0\1\11"+
    "\1\4\1\11\2\4\6\11\1\4\2\11\1\4\2\11"+
    "\1\4\7\11\3\0\1\33\5\0\1\33\7\11\7\0"+
    "\1\33\4\0\2\11\2\0\4\11\1\51\12\11\1\52"+
    "\2\11\1\53\6\11\12\0\7\11\14\0\2\11\2\0"+
    "\1\11\1\54\1\11\2\4\6\11\1\4\2\11\1\4"+
    "\2\11\1\4\7\11\3\0\1\33\5\0\1\33\7\11"+
    "\7\0\1\33\4\0\2\11\2\0\1\11\1\4\1\11"+
    "\2\4\1\11\1\55\4\11\1\4\2\11\1\4\2\11"+
    "\1\4\7\11\3\0\1\33\5\0\1\33\7\11\7\0"+
    "\1\33\4\0\2\11\2\0\13\11\1\56\4\11\1\57"+
    "\10\11\12\0\7\11\14\0\2\11\2\0\31\11\12\0"+
    "\7\11\14\0\2\11\2\0\1\11\1\60\11\11\1\61"+
    "\15\11\12\0\7\11\14\0\2\11\2\0\10\11\1\62"+
    "\10\11\1\63\7\11\12\0\7\11\14\0\2\11\2\0"+
    "\5\11\1\64\23\11\12\0\7\11\14\0\2\11\2\0"+
    "\1\11\1\4\1\11\2\4\4\11\1\65\1\11\1\4"+
    "\2\11\1\4\2\11\1\4\7\11\3\0\1\33\5\0"+
    "\1\33\7\11\7\0\1\33\4\0\2\11\2\0\10\11"+
    "\1\66\20\11\12\0\7\11\14\0\2\11\2\0\1\11"+
    "\1\67\14\11\1\70\12\11\12\0\7\11\14\0\2\11"+
    "\2\0\20\11\1\71\10\11\12\0\7\11\14\0\2\11"+
    "\2\0\11\11\1\72\17\11\12\0\7\11\14\0\2\11"+
    "\34\0\1\73\1\74\71\0\1\73\71\0\1\23\37\0"+
    "\1\33\1\0\2\33\6\0\1\33\2\0\1\33\2\0"+
    "\1\33\11\0\1\73\1\33\5\0\1\33\16\0\1\33"+
    "\45\0\1\73\77\0\1\75\1\76\2\0\1\75\1\0"+
    "\1\75\57\0\1\32\71\0\1\77\1\100\32\0\1\33"+
    "\1\0\2\33\6\0\1\33\2\0\1\33\2\0\1\33"+
    "\12\0\1\33\5\0\1\33\16\0\1\33\33\0\1\101"+
    "\17\0\2\34\2\0\1\34\1\0\1\34\1\102\26\0"+
    "\1\103\11\0\1\104\1\0\1\101\17\0\1\105\1\106"+
    "\1\104\1\0\1\106\1\103\1\106\1\102\74\0\1\36"+
    "\73\0\1\36\72\0\2\41\11\0\1\33\1\0\2\33"+
    "\6\0\1\33\2\0\1\33\2\0\1\33\12\0\1\33"+
    "\5\0\1\33\15\0\1\41\1\42\7\0\63\107\1\110"+
    "\2\0\4\107\1\0\1\44\62\0\2\44\3\0\1\44"+
    "\64\111\2\0\1\112\3\111\1\0\31\11\14\0\2\11"+
    "\1\0\1\11\15\0\1\113\1\11\2\0\2\11\1\114"+
    "\26\11\12\0\7\11\14\0\2\11\2\0\5\11\1\115"+
    "\23\11\12\0\7\11\14\0\2\11\2\0\23\11\1\116"+
    "\5\11\12\0\7\11\14\0\2\11\2\0\1\11\1\4"+
    "\1\11\2\4\1\11\1\117\4\11\1\4\2\11\1\4"+
    "\2\11\1\4\7\11\3\0\1\33\5\0\1\33\7\11"+
    "\7\0\1\33\4\0\2\11\2\0\10\11\1\120\20\11"+
    "\12\0\7\11\14\0\2\11\2\0\6\11\1\121\22\11"+
    "\12\0\7\11\14\0\2\11\2\0\2\11\1\122\26\11"+
    "\12\0\7\11\14\0\2\11\2\0\1\11\1\120\27\11"+
    "\12\0\7\11\14\0\2\11\2\0\11\11\1\123\17\11"+
    "\12\0\7\11\14\0\2\11\2\0\12\11\1\124\16\11"+
    "\12\0\7\11\14\0\2\11\2\0\5\11\1\125\23\11"+
    "\12\0\7\11\14\0\2\11\2\0\13\11\1\126\15\11"+
    "\12\0\7\11\14\0\2\11\2\0\5\11\1\127\23\11"+
    "\12\0\7\11\14\0\2\11\2\0\16\11\1\130\12\11"+
    "\12\0\7\11\14\0\2\11\2\0\13\11\1\52\15\11"+
    "\12\0\7\11\14\0\2\11\2\0\10\11\1\131\20\11"+
    "\12\0\7\11\14\0\2\11\2\0\2\11\1\132\26\11"+
    "\12\0\7\11\14\0\2\11\2\0\24\11\1\133\4\11"+
    "\12\0\7\11\14\0\2\11\34\0\1\73\102\0\2\75"+
    "\2\0\1\75\1\0\1\75\1\102\26\0\1\103\11\0"+
    "\1\104\22\0\1\134\1\104\1\0\1\134\1\103\1\134"+
    "\1\102\16\0\1\135\1\136\36\135\1\137\23\135\2\140"+
    "\3\135\1\136\64\100\2\0\4\100\6\0\1\141\127\0"+
    "\2\102\2\0\1\102\1\0\1\102\64\0\1\142\4\0"+
    "\1\142\23\0\1\143\3\0\1\143\1\0\1\143\3\0"+
    "\3\143\7\0\1\143\13\0\2\143\1\0\4\143\43\0"+
    "\1\101\17\0\2\105\2\0\1\105\1\0\1\105\43\0"+
    "\1\101\17\0\1\105\1\106\2\0\1\106\1\0\1\106"+
    "\20\0\3\11\1\52\25\11\12\0\7\11\14\0\2\11"+
    "\2\0\11\11\1\144\17\11\12\0\7\11\14\0\2\11"+
    "\2\0\10\11\1\145\20\11\12\0\7\11\14\0\2\11"+
    "\2\0\7\11\1\132\21\11\12\0\7\11\14\0\2\11"+
    "\2\0\10\11\1\52\20\11\12\0\7\11\14\0\2\11"+
    "\2\0\11\11\1\146\17\11\12\0\7\11\14\0\2\11"+
    "\2\0\12\11\1\52\16\11\12\0\7\11\14\0\2\11"+
    "\2\0\16\11\1\147\12\11\12\0\7\11\14\0\2\11"+
    "\2\0\11\11\1\52\17\11\12\0\7\11\14\0\2\11"+
    "\2\0\11\11\1\150\17\11\12\0\7\11\14\0\2\11"+
    "\2\0\2\11\1\151\26\11\12\0\7\11\14\0\2\11"+
    "\2\0\6\11\1\152\22\11\12\0\7\11\14\0\2\11"+
    "\2\0\12\11\1\122\16\11\12\0\7\11\14\0\2\11"+
    "\2\0\12\11\1\121\16\11\12\0\7\11\14\0\2\11"+
    "\2\0\10\11\1\124\20\11\12\0\7\11\14\0\2\11"+
    "\2\0\27\11\1\153\1\11\12\0\7\11\14\0\2\11"+
    "\46\0\1\134\2\0\1\134\1\0\1\134\17\0\40\154"+
    "\1\155\23\154\2\156\5\154\1\157\36\154\1\155\23\154"+
    "\2\140\3\154\1\157\40\154\1\155\1\160\22\154\2\156"+
    "\4\154\1\156\1\140\36\156\1\161\23\156\2\140\3\156"+
    "\1\140\1\0\13\11\1\162\15\11\12\0\7\11\14\0"+
    "\2\11\2\0\11\11\1\163\17\11\12\0\7\11\14\0"+
    "\2\11\2\0\25\11\1\52\3\11\12\0\7\11\14\0"+
    "\2\11\2\0\4\11\1\164\24\11\12\0\7\11\14\0"+
    "\2\11\2\0\4\11\1\165\24\11\12\0\7\11\14\0"+
    "\2\11\2\0\13\11\1\166\15\11\12\0\7\11\14\0"+
    "\2\11\2\0\13\11\1\167\15\11\12\0\7\11\14\0"+
    "\2\11\1\0\40\156\1\161\31\156\40\170\1\171\23\170"+
    "\2\0\4\170\40\156\1\161\1\141\30\156\1\0\17\11"+
    "\1\172\11\11\12\0\7\11\14\0\2\11\2\0\22\11"+
    "\1\173\6\11\12\0\7\11\14\0\2\11\2\0\3\11"+
    "\1\122\25\11\12\0\7\11\14\0\2\11\2\0\14\11"+
    "\1\52\14\11\12\0\7\11\14\0\2\11\2\0\4\11"+
    "\1\52\24\11\12\0\7\11\14\0\2\11\2\0\13\11"+
    "\1\174\15\11\12\0\7\11\14\0\2\11\1\0\40\170"+
    "\1\171\1\160\22\170\2\0\4\170\1\0\16\11\1\175"+
    "\12\11\12\0\7\11\14\0\2\11\2\0\11\11\1\176"+
    "\17\11\12\0\7\11\14\0\2\11\2\0\16\11\1\177"+
    "\12\11\12\0\7\11\14\0\2\11\2\0\15\11\1\124"+
    "\13\11\12\0\7\11\14\0\2\11\2\0\4\11\1\200"+
    "\24\11\12\0\7\11\14\0\2\11\2\0\30\11\1\52"+
    "\12\0\7\11\14\0\2\11\2\0\5\11\1\122\23\11"+
    "\12\0\7\11\14\0\2\11\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6380];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\27\1\1\11\3\1\1\11\6\1\1\11"+
    "\25\1\1\11\5\1\1\0\1\1\3\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\25\1\1\11\12\1\3\0"+
    "\2\1\1\0\6\1\2\0\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[128];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;
    public int line;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 230) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = yytext(); line = yyline;return PUNCTUATION;
            }
          case 14: break;
          case 2: 
            { lexeme = yytext(); line = yyline;return ERROR;
            }
          case 15: break;
          case 3: 
            { lexeme = yytext(); line = yyline;return IDENTIFIER;
            }
          case 16: break;
          case 4: 
            { lexeme = yytext(); line = yyline;return COMPARISON_OPERATOR;
            }
          case 17: break;
          case 5: 
            { lexeme = yytext(); line = yyline;return ARITHMETIC_OPERATOR;
            }
          case 18: break;
          case 6: 
            { lexeme = yytext(); line = yyline;return LOGICAL_OPERATOR;
            }
          case 19: break;
          case 7: 
            { lexeme = yytext(); line = yyline;return CONSTANT;
            }
          case 20: break;
          case 8: 
            { lexeme = yytext(); line = yyline;return NEWLINES;
            }
          case 21: break;
          case 9: 
            { lexeme = yytext(); line = yyline;return WHITESPACE;
            }
          case 22: break;
          case 10: 
            { lexeme = yytext(); line = yyline;return RESERVED_WORD;
            }
          case 23: break;
          case 11: 
            { lexeme = yytext(); line = yyline; return ERROR;
            }
          case 24: break;
          case 12: 
            { lexeme = yytext(); line = yyline;return COMMENT;
            }
          case 25: break;
          case 13: 
            { lexeme = yytext();line = yyline; return COMMENT_ERROR;
            }
          case 26: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
