
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 11 20:02:05 CST 2018
//----------------------------------------------------

package analizador_lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Comma = 33;
  public static final int LeftParenthesis = 29;
  public static final int Negation = 36;
  public static final int READLINE = 22;
  public static final int RightBrace = 39;
  public static final int Equal = 35;
  public static final int DOUBLE = 3;
  public static final int INTERFACE = 10;
  public static final int INT = 2;
  public static final int LeftBracket = 31;
  public static final int FOR = 14;
  public static final int Logical_Op = 41;
  public static final int Semicolon = 28;
  public static final int READINTEGER = 21;
  public static final int RightBracket = 32;
  public static final int BOOL = 4;
  public static final int DOUBLECONSTANT = 48;
  public static final int CLASS = 7;
  public static final int Point = 40;
  public static final int NEWARRAY = 20;
  public static final int RightParenthesis = 30;
  public static final int BOOLCONSTANT = 24;
  public static final int IF = 11;
  public static final int THIS = 18;
  public static final int GETBYTE = 26;
  public static final int INTCONSTANT = 47;
  public static final int SETBYTE = 27;
  public static final int EOF = 0;
  public static final int ident = 45;
  public static final int RETURN = 15;
  public static final int STRINGCONSTANT = 46;
  public static final int LeftBrace = 38;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int NULL = 25;
  public static final int Greater = 44;
  public static final int BREAK = 16;
  public static final int VOID = 6;
  public static final int ELSE = 12;
  public static final int Less = 43;
  public static final int WHILE = 13;
  public static final int EXTENDS = 8;
  public static final int Arithmetic_Op = 34;
  public static final int Comparison_op = 37;
  public static final int STRING = 5;
  public static final int MALLOC = 23;
  public static final int IMPLEMENTS = 9;
  public static final int PRINT = 17;
  public static final int EXCLA = 42;
}

