
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 07 23:23:56 CST 2018
//----------------------------------------------------

package analizador_lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Comma = 36;
  public static final int bool = 4;
  public static final int LeftParenthesis = 32;
  public static final int Negation = 39;
  public static final int RightBrace = 42;
  public static final int this = 18;
  public static final int doubleConstant = 25;
  public static final int Equal = 38;
  public static final int intConstant = 24;
  public static final int null = 28;
  public static final int implements = 9;
  public static final int LeftBracket = 34;
  public static final int string = 5;
  public static final int void = 6;
  public static final int class = 7;
  public static final int stringConstant = 27;
  public static final int Semicolon = 31;
  public static final int RightBracket = 35;
  public static final int else = 12;
  public static final int Point = 43;
  public static final int boolConstant = 26;
  public static final int RightParenthesis = 33;
  public static final int ReadLine = 22;
  public static final int EOF = 0;
  public static final int ident = 44;
  public static final int break = 16;
  public static final int ReadInteger = 21;
  public static final int LeftBrace = 41;
  public static final int error = 1;
  public static final int double = 3;
  public static final int Print = 17;
  public static final int NewArray = 20;
  public static final int while = 13;
  public static final int if = 11;
  public static final int GetByte = 29;
  public static final int int = 2;
  public static final int SetByte = 30;
  public static final int New = 19;
  public static final int for = 14;
  public static final int Malloc = 23;
  public static final int Arithmetic_Op = 37;
  public static final int EXTENDS = 8;
  public static final int interface = 10;
  public static final int Comparison_op = 40;
  public static final int return = 15;
}

